//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Computer.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_COMPUTER_H)
#define _COMPUTER_H


class Computer {
};

#endif  //_COMPUTER_H
