//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_COMPANY_H)
#define _COMPANY_H


class Company {
};

#endif  //_COMPANY_H
