//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CPU.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_CPU_H)
#define _CPU_H


class CPU {
};

#endif  //_CPU_H
