//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.cpp
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#include "Customer.h"

vector<Order>& Customer::GetOrders() {

}

