//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_CUSTOMER_H)
#define _CUSTOMER_H


class Customer {
public:
	vector<Order>& GetOrders();
private:
	vector<Order> orders_;
};

#endif  //_CUSTOMER_H
