//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_DEPARTMENT_H)
#define _DEPARTMENT_H


class Department {
};

#endif  //_DEPARTMENT_H
