//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Employee.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_EMPLOYEE_H)
#define _EMPLOYEE_H


class Employee {
};

#endif  //_EMPLOYEE_H
