//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MainBoard.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_MAINBOARD_H)
#define _MAINBOARD_H


class MainBoard {
};

#endif  //_MAINBOARD_H
