//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Manager.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_MANAGER_H)
#define _MANAGER_H

#include "Employee.h"

class Manager : public Employee, public Employee, public Employee {
};

#endif  //_MANAGER_H
