//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Master.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_MASTER_H)
#define _MASTER_H


class Master {
public:
	void Feed(int Pet& pet);
};

#endif  //_MASTER_H
