//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Master.cpp
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#include "Master.h"

void Master::Feed(int Pet& pet) {

}

