//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Memory.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_MEMORY_H)
#define _MEMORY_H


class Memory {
};

#endif  //_MEMORY_H
