//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_ORDER_H)
#define _ORDER_H


class Order {
};

#endif  //_ORDER_H
