//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pet.h
//  @ Date : 2012/11/6
//  @ Author : 
//
//


#if !defined(_PET_H)
#define _PET_H


class Pet {
};

#endif  //_PET_H
