// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#if !defined(AFX_STDAFX_H__BB945E23_FDF6_11D1_8CC3_00A0C9C8E50D__INCLUDED_)
#define AFX_STDAFX_H__BB945E23_FDF6_11D1_8CC3_00A0C9C8E50D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include <atlbase.h>

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STDAFX_H__BB945E23_FDF6_11D1_8CC3_00A0C9C8E50D__INCLUDED_)
