//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ATLInternals.rc
//
#define IDS_PROJNAME                    100
#define IDR_SOAPBOX                     101
#define IDS_SOAPBOXDESC                 101
#define IDR_DEMAGOGUE                   102
#define IDR_EARPOLITIC                  103
#define IDD_ABOUTBOX                    103
#define IDR_ATLInternals                104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         206
#define _APS_NEXT_SYMED_VALUE           144
#endif
#endif
